#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "admidio"
name = "Admidio"
description.en = "Management system for websites of organizations and groups"
description.fr = "Application de gestion des membres d'une association, d'un groupe ou d'une organisation"
version = "5.0.8~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.admidio.org/"
demo = "https://www.admidio.org/demo/system/login.php"
admindoc = "https://www.admidio.org/dokuwiki/doku.php?id=en:2.0:index"
code = "https://github.com/Admidio/admidio"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "300M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/admidio"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Admidio/admidio/archive/refs/tags/v5.0.8.zip"
    sha256 = "ccfcd213ca387c9f68f8bf0231826224fe767176daa5c32ee6d68de2ba61ae4e"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
	allow_email = true
    
    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    group = "www-data:rwx"
    subdirs = ["photos", "documents"]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.apt]
    packages = [
        "mariadb-server",
        "redis-server",
        "imagemagick",
        "php-pear",
        "php-db",
        "php8.4-uploadprogress",
        "php-xmlrpc",
        "php8.4-apcu",
        "php8.4-bcmath",
        "php8.4-bz2",
        "php8.4-curl",
        "php8.4-fpm",
        "php8.4-gd",
        "php8.4-gmp",
        "php8.4-igbinary",
        "php8.4-imagick",
        "php8.4-imap",
        "php8.4-intl",
        "php8.4-ldap",
        "php8.4-mbstring",
        "php8.4-redis",
        "php8.4-soap",
        "php8.4-tidy",
        "php8.4-xmlrpc",
        "php8.4-xml",
        "php8.4-zip",
        "php8.4-mysql",
        
    ]
   
    [resources.database]
    type = "mysql"
    
    [resources.composer]
    version = "2.9.3"
