#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "admidio"
name = "Admidio"
description.en = "Management system for websites of organizations and groups"
description.fr = "Management system for websites of organizations and groups"
version = "5.0.8~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "GPL-2.0-only"
website = "https://www.admidio.org/"
demo = "https://www.admidio.org/demo/system/login.php"
admindoc = "https://www.admidio.org/dokuwiki/doku.php?id=en:2.0:index"
code = "https://github.com/Admidio/admidio"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "1000M"
ram.build = "1500M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.mail_user]
    type = "string"
    ask.en = "Email from"
    default = "no-reply"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Admidio/admidio/archive/refs/tags/v5.0.8.tar.gz"
    sha256 = "7849cedf1b3c65c74481fb62ee3bb33b1ce019976cb57ec802b42124b16da7ba"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
	allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.apt]
    packages = [
        "postgresql",
        "redis-server",
        "imagemagick",
        "php-pear",
        "php-db",
        "php8.4-uploadprogress",
        "php-xmlrpc",
        "php8.4-apcu",
        "php8.4-bcmath",
        "php8.4-bz2",
        "php8.4-curl",
        "php8.4-fpm",
        "php8.4-gd",
        "php8.4-gmp",
        "php8.4-igbinary",
        "php8.4-imagick",
        "php8.4-imap",
        "php8.4-intl",
        "php8.4-ldap",
        "php8.4-mbstring",
        "php8.4-pgsql",
        "php8.4-redis",
        "php8.4-soap",
        "php8.4-tidy",
        "php8.4-xmlrpc",
        "php8.4-xml",
        "php8.4-zip",
    ]
   
    [resources.database]
    type = "postgresql"
