#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx
ynh_config_add --template="config.php" --destination="$install_dir/adm_my_files/config.php"

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

## do any changes to files that reference specific installation domain/path, i.e. regenerate configs etc

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
