#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=1000M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# INSTALL COMPOSER DEPENDENCIES
#=================================================

ynh_script_progression "Installing composer dependencies..."
pushd "$install_dir"

ynh_composer_exec install --no-dev
popd

#=================================================
# SET PERMISSIONS
#================================================

ln -s "$data_dir/photos" "$install_dir/adm_my_files/photos"
ln -s "$data_dir/documents" "$install_dir/adm_my_files/documents_monorg"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

ynh_config_add_logrotate

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Setting up application with CURL..."

ynh_local_curl "/install/installation.php?step=welcome&mode=check" "adm_system_language=$LANG"
ynh_local_curl "/install/installation.php?step=connect_database" \
    "adm_db_type=MariaDB" \
    "adm_db_host=localhost" \
    "adm_db_port=3308" \
    "adm_db_name=$db_name" \
    "adm_db_username=$db_user" \
    "adm_db_password=$db_pwd" \
    "adm_table_prefix=adm"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
