#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

ynh_app_setting_set --key=php_upload_max_filesize --value=1000M

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# INSTALL COMPOSER DEPENDENCIES
#=================================================

ynh_script_progression "Installing composer dependencies..."
pushd "$install_dir"

ynh_composer_exec install --no-dev
popd

#=================================================
# SET PERMISSIONS
#================================================

ln -s "$data_dir/photos" "$install_dir/adm_my_files/photos"
ln -s "$data_dir/documents" "$install_dir/adm_my_files/documents_monorg"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_phpfpm

ynh_config_add_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
