#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers


#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="adm_my_files adm_plugins themes"


#=================================================
# INSTALL COMPOSER DEPENDENCIES
#=================================================

ynh_script_progression "Installing composer dependencies..."
pushd "$install_dir"
# ynh_composer_install
ynh_composer_exec install --no-dev
popd

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ln -s "$data_dir" "$install_dir/adm_my_files/photos"
ynh_config_add_nginx

ynh_config_add_phpfpm

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
